## Day 51 & 52 of 100DaysOfCode 🐍
### Python Library - NumPy

#### **NumPy 🔢 🧮**

NumPy is a Python library, stands for **Numerical Python**, used for working with arrays.

#### **Purpose of Numpy 🔢 🧮**

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- In NumPy, the array object is called `ndarray` which provides a lot of supporting functions that make working with `ndarray` very easy.

- Most importantly, NumPy is faster than Lists (In NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently).

#### **Installation of NumPy**



In [ ]:
!pip install numpy

#### **Importing NumPy**


In [ ]:
import numpy as np

#### **Example**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### **Checking the NumPy Version**

In [ ]:
print(np.__version__)

1.23.5


### **NumPy Creating Arrays**

#### **Create a NumPy ndarray Object**

- NumPy is used to work with arrays. The array object in NumPy is called **ndarray**. We can create a NumPy **ndarray** object by using the `array()` function.



In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


#### **1-D Arrays**

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [ ]:
# Create a 1-D array containing the values 1,2,3,4,5

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### **2-D Arrays**

An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### **3-D Arrays**

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### **Checking Number of Dimensions**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
# Check how many dimensions the arrays have

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### **Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, we can define the number of dimensions by using the `ndmin` argument.

In [ ]:
# Create an array with 5 dimensions and verify that it has 5 dimensions

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


#### **Exercise - 1**

In [ ]:
#Insert the correct method for creating a NumPy array

arr = np.array([1, 2, 3, 4, 5])

#### **Exercise - 2**

In [ ]:
#Insert the correct argument for creating a NumPy array with 2 dimensions

arr = np.array([1, 2, 3, 4], ndmin=2)

#### **Exercise - 3**

In [ ]:
# Insert the correct syntax for checking the number of dimension of a NumPy array

arr = np.array([1, 2, 3, 4])

print(arr.ndim)

1
