## Day 53 & 54 of 100DaysOfCode 🐍
### Python Library - NumPy Arrays (Joining, Splitting, Searching, Sorting, Filtering)


#### **Joining NumPy Arrays**

- Joining means putting contents of two or more arrays in a single array.

- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

- To join to the `concatenate()` function, along with the axis. If axis is not explicitly passed, it is taken as 0.



In [ ]:
# Joining two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1)

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


##### Exercise

In [ ]:
# Use a correct NumPy method to join two arrays into a single array.

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### **Splitting NumPy Arrays**

- Splitting is reverse operation of Joining. Joining merges multiple arrays into one and Splitting breaks one array into multiple.
- We use `array_split()` for splitting arrays, we pass it the array we want to split and the number of splits.


In [ ]:
# Spliting the array in 3 parts

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Spliting the array in 4 parts

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


##### **Split Into Arrays**

- The return value of the array_split() method is an array containing each of the split as an array.

- Use the same syntax when splitting 2-D arrays.



In [ ]:
# Accessing the splitted arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


##### Use the `hsplit()` method to split the 2-D array into three 2-D arrays along rows.

> Similar alternates to `vstack()` and `dstack()` are available as `vsplit(`) and `dsplit()`.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


#### **Searching Arrays**
- We can search an array for a certain value, and return the indexes that get a match. To search an array, use the `where()` method.

In [ ]:
# Finding the indexes where the value is 4

arr = np.array([1, 2, 3, 4, 5, 4])

x = np.where(arr == 4)

print(x) # Meaning that the value 4 is present at index 3, and 5

(array([3, 5]),)


In [ ]:
# Finding the indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
# Finding the indexes where the value 7 should be inserted

arr = np.array([5, 6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

2


In [ ]:
# Finding the indexes where the values 2, 4, and 6 should be inserted

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


##### Exercise

In [ ]:
# Using the correct NumPy method to find all items with the value 4

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


#### **Sorting Arrays**

- Sorting means putting elements in an ordered sequence. Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

- The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

In [ ]:
# Sorting the array

arr = np.array([4, 5, 3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3 4 5]


In [ ]:
# Sort the array alphabetically

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
# Sorting a boolean array

arr = np.array([True, False, True, False])

print(np.sort(arr))

[False False  True  True]


Sorting a 2-D Array

- Using the `sort()` method on a 2-D array, both arrays will be sorted:

In [ ]:
arr = np.array([[2, 0, 1], [4, 3, 5]])

print(np.sort(arr))

[[0 1 2]
 [3 4 5]]


##### Exercise

In [ ]:
# Use the correct NumPy method to return a sorted array

arr = np.array([3, 2, 0, 5, 1, 4])

x = np.sort(arr)

print(x)

[0 1 2 3 4 5]


#### **Filtering Arrays**

- In NumPy, we can filter an array using a boolean index list. A boolean index list is a list of booleans corresponding to indexes in the array.

In [ ]:
# Create an array from the elements on index 0 and 2

arr = np.array([11, 12, 13, 14, 15])

x = [True, False, True, False, True]

newarr = arr[x]

print(newarr)

[11 13 15]


In [ ]:
# Creating a filter array that will return only values higher than 12

arr = np.array([10, 11, 12, 13, 14, 15])

filter_arr = arr > 12

newarr = arr[filter_arr]

print(newarr)

[13 14 15]
