## Day 53 of 100DaysOfCode 🐍
### NumPy Arrays (Shaping, Reshaping, Iterating)

#### **Shaping NumPy Arrays**

- NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements.

In [ ]:
# Printing the shape of a 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
# Creating an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


##### Exercise

In [ ]:
# Using the correct NumPy syntax to check the shape of an array

arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

(5,)


#### **Reshaping NumPy Arrays**

- Reshaping means changing the shape of an array.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

##### Exercise

In [ ]:
# Using the correct NumPy method to change the shape of an array from 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Use a correct NumPy method to change the shape of an array from 2-D to 1-D

arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(-1)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### **Iterating NumPy Arrays**

- Iterating means going through elements one by one.

- As we deal with multi-dimensional arrays in numpy, we can do this using basic `for` loop of python.

In [ ]:
# Iterating on the elements of the following 1-D array

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterating on the elements of the following 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
# Iterate on each scalar element of the 2-D array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterating on the elements of the following 3-D array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x represents the 2-D array:")
  print(x)

x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


##### **Iterating Arrays Using nditer()**

- The function `nditer()` is a helping function that can be used from very basic to very advanced iterations.

In [ ]:
# Iterate through the following 3-D array using nditer() function

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
